name: Bug report
description: Create a report to help us improve
title: ''
labels: ''
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.
  
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug in detail

  - type: markdown
    attributes:
      value: |
        **To Reproduce**
        Steps to reproduce the behavior:

  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: markdown
    attributes:
      value: |
        **Expected behavior**
        A clear and concise description of what you expected to happen.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior

  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Add screenshots here

  - type: markdown
    attributes:
      value: |
        **Script and Device's info (please complete the following information):**

  - type: input
    id: linux-distribution
    attributes:
      label: Linux Distribution
      description: e.g. Ubuntu (Version)
      placeholder: Enter your Linux distribution and version

  - type: input
    id: script-version
    attributes:
      label: Script Version
      description: Run `cat (script with issue) | grep VERSION`
      placeholder: Enter the script version

  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context about the problem here.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Add additional context
