#!/bin/bash

ConfigLocation=""
arg1="$1"
arg2="$2"
arg3="$3"
VERSION="1.0"
DONE=false
ROOT=false
USER="undefined"
RESPOND="undefined"
answer="undefined"
TEMP_DIR=".lilsitemp"
CONFIG_FILE="$TEMP_DIR/lilsi.conf"

echo "LilInstaller $VERSION"

# Main function to check what arg was inputted
function main {
    # Checks if you're root
    USER=$(whoami)
    if [[ "$USER" == "root" ]]; then
        ROOT=true
    else
        ROOT=false
        echo "[Info] You're not running as root. Just keep that in mind =D"
    fi
    # Checks if required dependencies are installed
    check_dependencies
    
    # Check if the script is properly setup
    check_config $ConfigLocation

    # Check command arguments
    case "$arg1" in 
        install)
            installl $arg2
            ;;
        update)
            update
            ;;
        *)
            echo "Usage: $0 [options]"
            echo "options:"
            echo "      install {script}: Installs a script from the LilScripts GitHub repository"
            echo "      update: Updates the script's code and list."
            ;;
    esac
}

# Function to check for configuration file
function check_config {
    local config_path="$1"
    if [[ -f "$config_path" ]]; then
        echo "[Info] Using configuration file at $config_path"
        source $config_path
    else
        echo "The installer's config wasn't found. If this isn't right, maybe you reinstalled the installer or the installer didn't properly add the config location to itself."
        yes_no "If you're actually new, would you like to setup the installer?"
        if [[ $RESPOND == true ]]; then
            setupp
        else
            yes_no "If this is an error, would you like to reconfigure the config location?"
            if [[ $RESPOND == true ]]; then
                promptt "Where is your config located? (Ex: /home/[user]/LilScripts/resources/lilsi.conf)"
                if [[ -f $answer ]]; then
                    # Test the config for validation
                    source $answer
                    if [[ -n $ScriptFiles && -n $InstallLocation ]]; then
                        echo "Config Validated!"
                        sed -i '/ ConfigLocation=/c\'"ConfigLocation=\"$ScriptFiles/lilsi.conf\"" "$0"
                        echo "Script Config Location corrected. Installer should now work! Try it now!"
                        exit 0
                    else
                        echo "Uhoh. The config isn't valid. We need a valid config to work. Check and confirm that the ScriptFiles and InstallLocation properties are set. Rerun the installer to redo the fixer."
                        exit $1
                    fi
                else
                    echo "The file doesn't exist. Rerun the script to redo the process."
                    exit 1
                fi
            else
                echo "Stopping installer"
                exit 0
            fi
        fi
    fi
}

# Function to check if required dependencies are installed or if it was overrided
function check_dependencies {
    WGET_PATH="$(command -v wget)"
    if [[ -z $WGET_PATH ]]; then
        echo "[Info] Missing Dependency wget. Please install it using your prefered package manager."
        exit 127
    fi
}

# Function to setup the script
function setupp {
    echo "[Setup] Begin Setup of LilScript Installer"
    echo "[Setup] Making temporary setup folder"
    mkdir -p "$TEMP_DIR"

    echo "[Setup] Downloading Index"
    wget "https://raw.githubusercontent.com/LilData777/LilScripts/refs/heads/main/Resources/lilscripts_index.list" -P "$TEMP_DIR"

    echo "[Setup] Creating Config"
    touch "$CONFIG_FILE"
    
    if [[ $ROOT == true ]]; then
        echo "# This is where the installer will install the scripts to" >> "$CONFIG_FILE"
        promptt "Where do you want to install scripts to? (default: /usr/local/bin)" "/usr/local/bin"
    else
        echo "# Note that setup of this config was done via a non-root user" >> "$CONFIG_FILE"
        echo "# This is where the installer will install the scripts to" >> "$CONFIG_FILE"
        promptt "Where do you want to install scripts to? (default: $HOME/lilscripts)" "$HOME/lilscripts"
    fi

    echo "InstallLocation=\"$answer\"" >> "$CONFIG_FILE"
    InstallLocation="$answer"
    [[ ! -d "$answer" ]] && mkdir -p "$answer"

    promptt "Where do you want extra files from scripts to be? (Ex: Logs, config, etc) (default: $InstallLocation/resources)" "$InstallLocation/resources"
    echo "# This is where scripts' files go to" >> "$CONFIG_FILE"
    echo "ScriptFiles=\"$answer\"" >> "$CONFIG_FILE"
    ScriptFiles="$answer"
    [[ ! -d "$answer" ]] && mkdir -p "$answer"

    echo "[Setup] Finalizing and moving everything"
    mv "$CONFIG_FILE" "$ScriptFiles"
    mv "$TEMP_DIR/lilscripts_index.list" "$ScriptFiles"
    
    # Correctly reference the script in the new directory
    sed -i '/ ConfigLocation=/c\'"ConfigLocation=\"$ScriptFiles/lilsi.conf\"" "$0"
    mv "$0" "$InstallLocation/lilsi"
    echo ""
    echo "Setup is complete. Config file was created at $ScriptFiles/lilsi.conf. The installer has moved to the location where all the scripts are ($InstallLocation) and is now called lilsi. The configuration location was appended to the script at line 3. If it is in /usr/local/bin, you can run the installer with lilsi. Hope that LilScripts become convenient to you. Please report issues at https://github.com/LilData777/LilScripts/issues"
}

function installl {
    echo "[Install] Reading Index"
    # Rest of install commands here
}

# Extra functions for other operations in this script
function yes_no {
    read -p "$1 (y/n) " RESPOND
    if [[ $RESPOND =~ ^[Yy](es)?$ ]]; then
        RESPOND=true
    else
        RESPOND=false
    fi
}

function promptt {
    read -p "$1 " answer
    if [[ -z "$answer" ]]; then
        if [[ -z "$2" ]]; then
            promptt "Blank answer not accepted. Try again. "
        else
            answer="$2"
        fi
    fi
}

# Function to update the script
function update {
    echo "[Updater] Comparing script version"
    mkdir "$ScriptFiles/$TEMP_DIR"
    wget "https://raw.githubusercontent.com/LilData777/LilScripts/refs/heads/main/Resources/lilscripts_index.list" -P "$ScriptFiles/$TEMP_DIR"
    grep 'lilsi - LilScript Installer' "$ScriptFiles/$TEMP_DIR/lilscripts_index.list" | sed -n 's/.*v\([0-9.]*\).*/\1/p'
    if [[ $VERSION < ONLINE_INDEX ]]; then
        echo "[Updater] Update available for Installer (Original: $VERSION > New: $ONLINE_INDEX)"
        yes_no "Would you like to update?"
        if [[ $RESPOND == true ]]; then
            echo "[Updater] Updating Index"
            cat "$ScriptFiles/$TEMP_DIR/lilscripts_index.list" > $ScriptFiles/lilscripts_index.list
            echo "[Updater] Updating Installer"
            wget "https://raw.githubusercontent.com/LilData777/LilScripts/refs/heads/main/Scripts/Installer%20Script/lilsi" -P "$ScriptFiles/$TEMP_DIR"
            cat "$ScriptFiles/$TEMP_DIR/lilsi" > ./$0
            # Stuff to update scripts will be here
            echo "[Updater] Update complete."
            exit 0
        fi
    else
        echo "[Updater] Not updating."
        exit 0
    fi
    sleep 2
    # Check for updates
    echo "[Updater] No new updates found!"
}

main
